server:
  ssl:
    key-store: classpath:account.jks
    key-store-password: changeit
    key-store-type: JKS
    enabled: false
  port: 8080
  servlet:
    context-path: /account

spring:
  sql:
    init:
      mode: never
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.7:3306/account?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&connectionCharacterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: Lx@12345678
