-- 账户表
CREATE TABLE IF NOT EXISTS T_ACCOUNT (
    AID INT(11) NOT NULL AUTO_INCREMENT COMMENT '账户ID',
    PROP VARCHAR(2) DEFAULT '1' COMMENT '属性: 1-资产 2-负债',
    OWNER VARCHAR(50) DEFAULT NULL COMMENT '所有人',
    ACCNAME VARCHAR(100) DEFAULT NULL COMMENT '账户名称',
    ACCOUNT VARCHAR(100) DEFAULT NULL COMMENT '账号',
    BALANCE DECIMAL(15,2) DEFAULT 0.00 COMMENT '余额',
    MTYPE VARCHAR(20) DEFAULT NULL COMMENT '账户类型',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '备注',
    CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    OPERATER VARCHAR(50) DEFAULT NULL COMMENT '操作人',
    PRIMARY KEY (AID),
    KEY idx_prop (PROP),
    KEY idx_owner (OWNER),
    KEY idx_accname (ACCNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='账户表';

-- 流水表
CREATE TABLE IF NOT EXISTS T_WATER (
    WID INT(11) NOT NULL AUTO_INCREMENT COMMENT '流水ID',
    AID INT(11) NOT NULL COMMENT '账户ID',
    TRDATE DATE DEFAULT NULL COMMENT '交易日期',
    TRADEKIND VARCHAR(2) DEFAULT '0' COMMENT '交易分类: 0-转账 1-居家 2-食品 3-交通 4-投资 5-还款',
    TRTYPE VARCHAR(2) DEFAULT '0' COMMENT '交易类型: 0-出金 1-入金',
    WACCOUNT VARCHAR(100) DEFAULT NULL COMMENT '对方账户',
    WACCNAME VARCHAR(100) DEFAULT NULL COMMENT '对方账户名',
    TRNUM DECIMAL(15,2) DEFAULT 0.00 COMMENT '交易金额',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '备注',
    OPPID VARCHAR(50) DEFAULT NULL COMMENT '对方账户ID',
    IFAUTO VARCHAR(2) DEFAULT '0' COMMENT '是否自动生成: 0-手动 1-自动',
    CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (WID),
    KEY idx_aid (AID),
    KEY idx_trdate (TRDATE),
    KEY idx_trtype (TRTYPE),
    KEY idx_tradekind (TRADEKIND)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='流水表';
