-- 账户表
CREATE TABLE IF NOT EXISTS T_ACCOUNT (
    AID INTEGER PRIMARY KEY AUTOINCREMENT,
    PROP VARCHAR(2) DEFAULT '1',
    OWNER VARCHAR(50),
    ACCNAME VARCHAR(100),
    ACCOUNT VARCHAR(100),
    BALANCE REAL DEFAULT 0,
    MTYPE VARCHAR(20),
    REMARK VARCHAR(500),
    CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    OPERATER VARCHAR(50)
);

-- 流水表
CREATE TABLE IF NOT EXISTS T_WATER (
    WID INTEGER PRIMARY KEY AUTOINCREMENT,
    AID INTEGER NOT NULL,
    TRDATE DATE,
    TRADEKIND VARCHAR(2) DEFAULT '0',
    TRTYPE VARCHAR(2) DEFAULT '0',
    WACCOUNT VARCHAR(100),
    WACCNAME VARCHAR(100),
    TRNUM REAL DEFAULT 0,
    REMARK VARCHAR(500),
    CREATETIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATETIME DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 创建索引
CREATE INDEX IF NOT EXISTS idx_account_prop ON T_ACCOUNT(PROP);
CREATE INDEX IF NOT EXISTS idx_water_aid ON T_WATER(AID);
CREATE INDEX IF NOT EXISTS idx_water_trdate ON T_WATER(TRDATE);
